# Generated by Django 5.2.14 on 2026-05-20 17:01

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='conversions/original/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv', 'json', 'docx', 'pdf'])], verbose_name='Исходный файл')),
                ('target_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel (XLSX)'), ('word', 'Word (DOCX)'), ('json', 'JSON')], max_length=10, verbose_name='Целевой формат')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='conversions/result/%Y/%m/%d/', verbose_name='Конвертированный файл')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('file_size_original', models.BigIntegerField(default=0, verbose_name='Размер исходного (байт)')),
                ('file_size_converted', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Размер результата (байт)')),
            ],
            options={
                'verbose_name': 'Конвертация файла',
                'verbose_name_plural': 'Конвертация файлов',
                'ordering': ['-created_at'],
            },
        ),
    ]
